-- 고정 라운드 점수판용 인덱스.
--
-- 라운드 식별자를 따로 두지 않고 `question_ids` 문자열 자체로 묶는다.
-- 공유 링크 재도전(`/play?from=<slug>`)은 같은 문제를 같은 순서로 다시
-- 풀고, 저장 경로가 항상 `JSON.stringify(순서대로의 id 배열)` 하나뿐이라
-- 같은 라운드의 row들은 이 컬럼이 바이트 단위로 동일하다.
--
-- 이렇게 하면 새 컬럼도 백필도 필요 없고 기존 row에도 그대로 적용된다.
-- 대안이던 "round_id 컬럼 + replay 시 상속"은 클라이언트가 `from`을 보내야
-- 해서 자기 점수를 임의의 라운드에 붙이는 표면이 생기는데, 그걸 막으려면
-- 결국 question_ids를 대조해야 한다 — 그럴 바엔 처음부터 이걸로 묶는다.
--
-- 5번 데일리 라운드도 문제 목록만 고정하면 같은 그룹핑에 그대로 얹힌다.
CREATE INDEX IF NOT EXISTS idx_shares_question_ids ON shares (question_ids);
